export const API_Cars = [
    {   
        brand: "Toyota",
        model: 'Corolla',
        year: 2022,
        price: 188060,
        category: "Sedan",
        machine: "2.0",
        fuel: "Gasolina/Etanol",
        cambio: "Automatico",
        doors: 4,
        color: "Cinza",
        km: 33000,
        pasteImage: "Toyota-Corolla",
        qntImg: 9,
        id: 0 ,
    },
    { 
        brand: "Peugeot",
        model: '208',
        year: 2023,
        price: 80330,
        category: "Hatch",
        machine: "1.6",
        fuel: "Gasolina/Etanol",
        cambio: "Automatico",
        doors: 4,
        color: "Azul",
        km: 36432,
        pasteImage: "Peugeot-208",
        qntImg: 9,
        id:1 ,
    },
    {   
        brand: "Jeep",
        model: 'Renegade',
        year: 2021,
        price: 102000,
        category: "SUV",
        machine: "1.8",
        fuel: "Gasolina/Etanol",
        cambio: "Mecanico",
        doors: 5,
        color: "Cinza",
        km: 26749,
        pasteImage: "Jeep-Renegade",
        qntImg: 9,
        id: 2,
    },
    {   
        brand: "Volkswagen",
        model: 'Voyage',
        year: 2023,
        price: 56930,
        category: "Sedan",
        machine: "1.0",
        fuel: "Gasolina/Etanol",
        cambio: "Mecanico",
        doors: 4,
        color: "Branco",
        km: 81300,
        pasteImage: "Volkswagen-Voyage",
        qntImg: 9,
        id: 3,
    },
    {   
        brand: "Citroen",
        model: 'C4',
        year: 2022,
        price: 97750,
        category: "SUV",
        machine: "1.6",
        fuel: "Gasolina/Etanol",
        cambio: "Mecanico",
        doors: 4,
        color: "Vermelho",
        km: 40304,
        pasteImage: "Citroen-C4",
        qntImg: 9,
        id: 4,
    },
    {   
        brand: "Renault",
        model: 'Oroch',
        year: 2023,
        price: 95310,
        category: "Picape",
        machine: "1.6",
        fuel: "Gasolina/Etanol",
        cambio: "Mecanico",
        doors: 4,
        color: "Branco",
        km: 40304,
        pasteImage: "Renault-Oroch",
        qntImg: 9,
        id: 5,
    },
    {   
        brand: "Renault",
        model: 'Captur',
        year: 2022,
        price: 108280,
        category: "SUV",
        machine: "1.3",
        fuel: "Gasolina/Etanol",
        cambio: "Automatico",
        doors: 4,
        color: "Azul",
        km: 49938,
        pasteImage: "Renault-Captur",
        qntImg: 9,
        id: 6,
    },
    {   
        brand: "Volkswagen",
        model: 'T-Cross',
        year: 2022,
        price: 122320,
        category: "SUV",
        machine: "1.4",
        fuel: "Gasolina/Etanol",
        cambio: "Automatico",
        doors: 4,
        color: "Azul",
        km: 72646,
        pasteImage: "Volkswagen-Tcross",
        qntImg: 9,
        id: 7,
    },
    {   
        brand: "BMW",
        model: '320i',
        year: 2022,
        price: 272470,
        category: "Sedan",
        machine: "2.0",
        fuel: "Gasolina/Etanol",
        cambio: "Automatico",
        doors: 5,
        color: "Branco",
        km: 18773,
        pasteImage: "Bmw-320i",
        qntImg: 7,
        id: 8,
    },
    {   
        brand: "Mitsubishi",
        model: 'Eclipse',
        year: 2023,
        price: 181890,
        category: "SUV",
        machine: "1.5",
        fuel: "Gasolina/Etanol",
        cambio: "Automatico",
        doors: 4,
        color: "Azul",
        km: 52001,
        pasteImage: "Mitsubishi-Eclipse",
        qntImg: 9,
        id: 9,
    },
    {   
        brand: "Chevrolet",
        model: 'Onix',
        year: 2023,
        price: 100370,
        category: "Sedan",
        machine: "1.0",
        fuel: "Gasolina/Etanol",
        cambio: "Automatico",
        doors: 4,
        color: "Preto",
        km: 9039,
        pasteImage: "Chevrolet-Onix",
        qntImg: 9,
        id: 10,
    },
    {   
        brand: "Nissan",
        model: 'Kicks',
        year: 2022,
        price: 112030,
        category: "SUV",
        machine: "1.6",
        fuel: "Gasolina/Etanol",
        cambio: "Automatico",
        doors: 4,
        color: "Preto",
        km: 39286,
        pasteImage: "Nissan-Kicks",
        qntImg: 9,
        id: 11,
    },
    {   
        brand: "Fiat",
        model: 'Cronos',
        year: 2022,
        price: 74790,
        category: "Sedan",
        machine: "1.3",
        fuel: "Gasolina/Etanol",
        cambio: "Mecanico",
        doors: 4,
        color: "Vermelho",
        km: 45810,
        pasteImage: "Fiat-Cronos",
        qntImg: 9,
        id: 12,
    },
    {   
        brand: "Fiat",
        model: 'Fiorino',
        year: 2022,
        price: 90499,
        category: "Furgão",
        machine: "1.4",
        fuel: "Gasolina/Etanol",
        cambio: "Mecanico",
        doors: 4,
        color: "Branco",
        km: 39702,
        pasteImage: "Fiat-Fiorino",
        qntImg: 9,
        id: 13,
    },
    {   
        brand: "Fiat",
        model: 'Doblo',
        year: 2021,
        price: 80990,
        category: "Mini-Van",
        machine: "1.8",
        fuel: "Gasolina/Etanol",
        cambio: "Mecanico",
        doors: 4,
        color: "Prata",
        km: 55109,
        pasteImage: "Fiat-Doblo",
        qntImg: 9,
        id: 14,
    },
    {   
        brand: "Ford",
        model: 'Ka',
        year: 2020,
        price: 55110,
        category: "Hatch",
        machine: "1.0",
        fuel: "Gasolina/Etanol",
        cambio: "Mecanico",
        doors: 4,
        color: "Prata",
        km: 50424,
        pasteImage: "Ford-Ka",
        qntImg: 9,
        id: 15,
    },
    {   
        brand: "Ford",
        model: 'Ecosport',
        year: 2020,
        price: 81500,
        category: "SUV",
        machine: "1.5",
        fuel: "Gasolina/Etanol",
        cambio: "Automatico",
        doors: 4,
        color: "Cinza",
        km: 50424,
        pasteImage: "Ford-Ecosport",
        qntImg: 7,
        id: 16,
    },
    {   
        brand: "Fiat",
        model: 'Strada',
        year: 2022,
        price: 84440,
        category: "Picape",
        machine: "1.4",
        fuel: "Gasolina/Etanol",
        cambio: "Automatico",
        doors: 4,
        color: "Cinza",
        km: 25922,
        pasteImage: "Fiat-Strada",
        qntImg: 7,
        id: 17,
    },
    {   
        brand: "Fiat",
        model: 'Cronos',
        year: 2022,
        price: 70740,
        category: "Sedan",
        machine: "1.3",
        fuel: "Gasolina/Etanol",
        cambio: "Mecanico",
        doors: 4,
        color: "Prata",
        km: 40500,
        pasteImage: "Fiat-Cronos2",
        qntImg: 8,
        id: 18,
    },
    {   
        brand: "Fiat",
        model: 'Argo',
        year: 2019,
        price: 59000,
        category: "Hatch",
        machine: "1.0",
        fuel: "Gasolina/Etanol",
        cambio: "Mecanico",
        doors: 4,
        color: "Branco",
        km: 40500,
        pasteImage: "Fiat-Argo2",
        qntImg: 9,
        id: 19,
    },
    {   
        brand: "Audi",
        model: 'A4',
        year: 2021,
        price: 245900,
        category: "Sedan",
        machine: "2.0",
        fuel: "Gasolina/Etanol",
        cambio: "Automatico",
        doors: 4,
        color: "Cinza",
        km: 26085,
        pasteImage: "Audi-A4",
        qntImg: 9,
        id: 20,
    },
    {   
        brand: "Audi",
        model: 'E-TRON',
        year: 2021,
        price: 245900,
        category: "SUV",
        machine: "2.0",
        fuel: "Gasolina/Etanol",
        cambio: "Automatico",
        doors: 4,
        color: "Preto",
        km: 12439,
        pasteImage: "Audi-Etron",
        qntImg: 9,
        id: 21,
    },
    {   
        brand: "Audi",
        model: 'A3',
        year: 2020,
        price: 150900,
        category: "Sedan",
        machine: "1.4",
        fuel: "Gasolina/Etanol",
        cambio: "Automatico",
        doors: 4,
        color: "Branco",
        km: 28236,
        pasteImage: "Audi-A3",
        qntImg: 8,
        id: 22,
    },
    {   
        brand: "Chery",
        model: 'Tiggo 8',
        year: 2022,
        price: 154190,
        category: "SUV",
        machine: "1.6",
        fuel: "Gasolina/Etanol",
        cambio: "Automatico",
        doors: 4,
        color: "Cinza",
        km: 42169,
        pasteImage: "Chery-Tiggo",
        qntImg: 9,
        id: 23,
    },
    {   
        brand: "Chery",
        model: 'Tiggo 8',
        year: 2022,
        price: 152730,
        category: "SUV",
        machine: "1.6",
        fuel: "Gasolina/Etanol",
        cambio: "Automatico",
        doors: 4,
        color: "Branco",
        km: 50392,
        pasteImage: "Chery-Tiggo8",
        qntImg: 9,
        id: 24,
    },
    {   
        brand: "Hyundai",
        model: 'Creta',
        year: 2022,
        price: 97990,
        category: "SUV",
        machine: "1.6",
        fuel: "Gasolina/Etanol",
        cambio: "Automatico",
        doors: 4,
        color: "Branco",
        km: 41230,
        pasteImage: "Hyundai-Creta",
        qntImg: 9,
        id: 25,
    },
    {   
        brand: "Land",
        model: 'Rover',
        year: 2017,
        price: 139940,
        category: "SUV",
        machine: "2.0",
        fuel: "Gasolina/Etanol",
        cambio: "Automatico",
        doors: 4,
        color: "Cinza",
        km: 90260,
        pasteImage: "Land-Rover",
        qntImg: 9,
        id: 26,
    },
    {   
        brand: "Jaguar",
        model: 'E-Pace',
        year: 2020,
        price: 271990,
        category: "SUV",
        machine: "2.0",
        fuel: "Gasolina/Etanol",
        cambio: "Automatico",
        doors: 4,
        color: "Cinza",
        km: 11159,
        pasteImage: "Jaguar-Epace",
        qntImg: 9,
        id: 27,
    },
    {   
        brand: "Volvo",
        model: 'XC40',
        year: 2019,
        price: 190000,
        category: "SUV",
        machine: "2.0",
        fuel: "Gasolina/Etanol",
        cambio: "Automatico",
        doors: 4,
        color: "Preto",
        km: 36635,
        pasteImage: "Volvo-XC40",
        qntImg: 9,
        id: 28,
    },
    {   
        brand: "Chevrolet",
        model: 'S-10',
        year: 2023,
        price: 220720,
        category: "Picape",
        machine: "2.8",
        fuel: "Gasolina/Etanol",
        cambio: "Mecanico",
        doors: 4,
        color: "Branco",
        km: 30746,
        pasteImage: "Chevrolet-S10",
        qntImg: 7,
        id: 29,
    },
    
    
]